version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-tmp:/tmp
      - textsum-vol:/static
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    depends_on:
      - web
  web:
    build: ./textprocessor
    restart: always
    volumes:
      - nginx-tmp:/tmp
      - textsum-vol:/code/static
    depends_on:
      - helper
  helper:
    image: busybox:latest
    volumes:
      - nginx-tmp:/tmp
      - textsum-vol:/static
    command: rm -rf /tmp/* && rm -rf /static/*

volumes:
    textsum-vol:
    nginx-tmp:
    certs:
    certs-data:
